// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9ZRh0hCbp5dDu76GmpQAj9cBRx4ZGbgA',
    appId: '1:804265617466:web:a3c3a55d152f2edd112d03',
    messagingSenderId: '804265617466',
    projectId: 'timetide-70715',
    authDomain: 'timetide-70715.firebaseapp.com',
    storageBucket: 'timetide-70715.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmlrUxKkFwbcFxjQkO1AB57PofwTM653M',
    appId: '1:804265617466:android:56fb724ca386f56d112d03',
    messagingSenderId: '804265617466',
    projectId: 'timetide-70715',
    storageBucket: 'timetide-70715.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI-wyr2kKEWn6c_DkT4IhAIfAKJc1ao7Y',
    appId: '1:804265617466:ios:c2d9f76e58aab1df112d03',
    messagingSenderId: '804265617466',
    projectId: 'timetide-70715',
    storageBucket: 'timetide-70715.appspot.com',
    iosBundleId: 'com.example.timeTide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI-wyr2kKEWn6c_DkT4IhAIfAKJc1ao7Y',
    appId: '1:804265617466:ios:c2d9f76e58aab1df112d03',
    messagingSenderId: '804265617466',
    projectId: 'timetide-70715',
    storageBucket: 'timetide-70715.appspot.com',
    iosBundleId: 'com.example.timeTide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9ZRh0hCbp5dDu76GmpQAj9cBRx4ZGbgA',
    appId: '1:804265617466:web:66bf4101f818bf06112d03',
    messagingSenderId: '804265617466',
    projectId: 'timetide-70715',
    authDomain: 'timetide-70715.firebaseapp.com',
    storageBucket: 'timetide-70715.appspot.com',
  );
}
